name: Guardar Resultado

on:
  push:
  workflow_dispatch:

jobs:
  hola:
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: ./tres-en-raya

    steps:
      - name: Descargar Codigo
        uses: actions/checkout@v4

      - name: En que carpeta estoy
        run: pwd

      - name: Listado
        run: ls -la

      - name: Instalar node
        uses: actions/setup-node@v4

      - name: Verificar node
        run: node --version

      - name: Verificar npm
        run: npm --version
        
      - name: Build Vite
        run: npx vite build